workspace: true

stages:
- rubocop

jobs:
  - name: test:rubocop
    stage: rubocop
    image: cimg/ruby:3.2.0
    script:
    - gem install rubocop
    - gem install rubocop-rails
    - gem install rubocop-performance
    - gem install rubocop-rspec
    - rubocop
